"""
Comprehensive Question Banks for AI Interview Coach
Provides up to 20 distinct, sequential questions across Easy, Medium, and Hard
for DSA, Machine Learning, System Design, Python, and General Engineering.
"""
from typing import Dict, List

EXPANDED_QUESTION_BANKS: Dict[str, Dict[str, List[str]]] = {
    "dsa": {
        "Easy": [
            "### Problem: Two Sum\nGiven an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`.\n\n**Test Cases**\n1. Input: nums = [2, 7, 11, 15], target = 9\n   Output: [0, 1]\n   Explanation: Because nums[0] + nums[1] == 9, we return [0, 1].\n2. Input: nums = [3, 2, 4], target = 6\n   Output: [1, 2]\n\n**Constraints & Requirements:**\n- 2 <= nums.length <= 10^4\n- Only one valid answer exists.\n- State Time ($O(N)$) and Space ($O(N)$) complexity.",
            "### Problem: Valid Anagram\nGiven two strings `s` and `t`, return `true` if `t` is an anagram of `s`, and `false` otherwise.\n\n**Test Cases**\n1. Input: s = \"anagram\", t = \"nagaram\"\n   Output: true\n   Explanation: All characters match with equal frequencies.\n2. Input: s = \"rat\", t = \"car\"\n   Output: false\n\n**Constraints & Requirements:**\n- 1 <= s.length, t.length <= 5 * 10^4\n- Solve in $O(N)$ Time and $O(1)$ auxiliary space for ASCII.",
            "### Problem: Reverse Linked List\nGiven the `head` of a singly linked list, reverse the list, and return the reversed list.\n\n**Test Cases**\n1. Input: head = [1, 2, 3, 4, 5]\n   Output: [5, 4, 3, 2, 1]\n   Explanation: The linked list pointers are reversed in-place.\n2. Input: head = []\n   Output: []\n\n**Constraints & Requirements:**\n- The number of nodes in the list is in range [0, 5000].\n- Walk through iterative pointer updates in $O(1)$ space.",
            "### Problem: Binary Search\nGiven a sorted array `nums` of integers and an integer `target`, return the index of `target` or `-1` if not found.\n\n**Test Cases**\n1. Input: nums = [-1, 0, 3, 5, 9, 12], target = 9\n   Output: 4\n   Explanation: 9 exists in nums and its index is 4.\n2. Input: nums = [-1, 0, 3, 5, 9, 12], target = 2\n   Output: -1\n\n**Constraints & Requirements:**\n- 1 <= nums.length <= 10^4, sorted in ascending order.\n- State Time ($O(\\log N)$) and explain midpoint integer overflow prevention.",
            "### Problem: Merge Two Sorted Lists\nMerge two sorted linked lists `list1` and `list2` and return it as a new sorted list.\n\n**Test Cases**\n1. Input: list1 = [1, 2, 4], list2 = [1, 3, 4]\n   Output: [1, 1, 2, 3, 4, 4]\n   Explanation: Merged into a non-decreasing sorted chain.\n2. Input: list1 = [], list2 = []\n   Output: []\n\n**Constraints & Requirements:**\n- The number of nodes in both lists is in range [0, 50].\n- Maintain $O(1)$ auxiliary space by relinking existing nodes.",
            "### Problem: Maximum Subarray\nGiven an integer array `nums`, find the contiguous subarray with the largest sum and return its sum.\n\n**Test Cases**\n1. Input: nums = [-2, 1, -3, 4, -1, 2, 1, -5, 4]\n   Output: 6\n   Explanation: The subarray [4, -1, 2, 1] has the largest sum 6.\n2. Input: nums = [1]\n   Output: 1\n3. Input: nums = [5, 4, -1, 7, 8]\n   Output: 23\n\n**Constraints & Requirements:**\n- 1 <= nums.length <= 10^5\n- State Kadane's algorithm invariant in $O(N)$ time and $O(1)$ space.",
            "### Problem: Valid Parentheses\nGiven a string `s` containing just the characters `'('`, `')'`, `'{'`, `'}'`, `'['` and `']'`, determine if the input string is valid.\n\n**Test Cases**\n1. Input: s = \"()[]{}\"\n   Output: true\n   Explanation: Every bracket is closed in correct order.\n2. Input: s = \"(]\"\n   Output: false\n3. Input: s = \"([)]\"\n   Output: false\n\n**Constraints & Requirements:**\n- 1 <= s.length <= 10^4\n- Use a stack in $O(N)$ time and $O(N)$ space.",
            "### Problem: Contains Duplicate\nGiven an integer array `nums`, return `true` if any value appears at least twice in the array, and return `false` if every element is distinct.\n\n**Test Cases**\n1. Input: nums = [1, 2, 3, 1]\n   Output: true\n   Explanation: Element 1 appears at index 0 and 3.\n2. Input: nums = [1, 2, 3, 4]\n   Output: false\n\n**Constraints & Requirements:**\n- 1 <= nums.length <= 10^5\n- Compare Hash Set ($O(N)$ time, $O(N)$ space) vs Sorting ($O(N \\log N)$ time, $O(1)$ space).",
            "### Problem: Climbing Stairs\nYou are climbing a staircase. It takes `n` steps to reach the top. Each time you can climb 1 or 2 steps. How many distinct ways can you climb to the top?\n\n**Test Cases**\n1. Input: n = 2\n   Output: 2\n   Explanation: 1 step + 1 step, or 2 steps.\n2. Input: n = 3\n   Output: 3\n   Explanation: (1+1+1), (1+2), (2+1).\n3. Input: n = 5\n   Output: 8\n\n**Constraints & Requirements:**\n- 1 <= n <= 45\n- State DP recurrence $dp[i] = dp[i-1] + dp[i-2]$ and $O(1)$ space optimization.",
            "### Problem: Best Time to Buy and Sell Stock\nYou are given an array `prices` where `prices[i]` is the price of a stock on the $i^{\\text{th}}$ day. Maximize your profit by choosing a single day to buy and a different day in the future to sell.\n\n**Test Cases**\n1. Input: prices = [7, 1, 5, 3, 6, 4]\n   Output: 5\n   Explanation: Buy on day 2 (price = 1) and sell on day 5 (price = 6), profit = 6 - 1 = 5.\n2. Input: prices = [7, 6, 4, 3, 1]\n   Output: 0\n\n**Constraints & Requirements:**\n- 1 <= prices.length <= 10^5\n- Solve in single pass $O(N)$ time and $O(1)$ auxiliary space.",
            "### Problem: Invert Binary Tree\nGiven the root of a binary tree, invert the tree, and return its root.\n\n**Test Cases**\n1. Input: root = [4, 2, 7, 1, 3, 6, 9]\n   Output: [4, 7, 2, 9, 6, 3, 1]\n   Explanation: Left and right subtrees swapped at each node.\n2. Input: root = [2, 1, 3]\n   Output: [2, 3, 1]\n\n**Constraints & Requirements:**\n- The number of nodes in tree is in range [0, 100].\n- State recursive and iterative BFS solutions.",
            "### Problem: Majority Element\nGiven an array `nums` of size `n`, return the majority element that appears more than $\\lfloor n/2 \\rfloor$ times.\n\n**Test Cases**\n1. Input: nums = [3, 2, 3]\n   Output: 3\n   Explanation: 3 appears 2 times out of 3.\n2. Input: nums = [2, 2, 1, 1, 1, 2, 2]\n   Output: 2\n\n**Constraints & Requirements:**\n- 1 <= nums.length <= 5 * 10^4\n- Solve in $O(N)$ time and $O(1)$ space using Boyer-Moore Voting Algorithm.",
            "### Problem: Move Zeroes\nGiven an integer array `nums`, move all 0's to the end of it while maintaining the relative order of the non-zero elements in-place.\n\n**Test Cases**\n1. Input: nums = [0, 1, 0, 3, 12]\n   Output: [1, 3, 12, 0, 0]\n   Explanation: Non-zero elements retain original order.\n2. Input: nums = [0]\n   Output: [0]\n\n**Constraints & Requirements:**\n- 1 <= nums.length <= 10^4\n- Must modify array in-place without copying.",
            "### Problem: Single Number\nGiven a non-empty array of integers `nums`, every element appears twice except for one. Find that single one.\n\n**Test Cases**\n1. Input: nums = [2, 2, 1]\n   Output: 1\n   Explanation: 1 appears only once.\n2. Input: nums = [4, 1, 2, 1, 2]\n   Output: 4\n\n**Constraints & Requirements:**\n- 1 <= nums.length <= 3 * 10^4\n- Solve in linear $O(N)$ time and $O(1)$ auxiliary space using Bitwise XOR.",
            "### Problem: Roman to Integer\nConvert a Roman numeral string `s` to an integer.\n\n**Test Cases**\n1. Input: s = \"III\"\n   Output: 3\n   Explanation: III = 3.\n2. Input: s = \"LVIII\"\n   Output: 58\n   Explanation: L = 50, V= 5, III = 3.\n3. Input: s = \"MCMXCIV\"\n   Output: 1994\n   Explanation: M = 1000, CM = 900, XC = 90 and IV = 4.\n\n**Constraints & Requirements:**\n- 1 <= s.length <= 15\n- Handle subtractive pairs cleanly.",
            "### Problem: Valid Palindrome\nGiven a string `s`, return `true` if it is a palindrome, considering only alphanumeric characters and ignoring cases.\n\n**Test Cases**\n1. Input: s = \"A man, a plan, a canal: Panama\"\n   Output: true\n   Explanation: \"amanaplanacanalpanama\" is a palindrome.\n2. Input: s = \"race a car\"\n   Output: false\n\n**Constraints & Requirements:**\n- 1 <= s.length <= 2 * 10^5\n- Solve using two pointers with $O(1)$ auxiliary memory.",
            "### Problem: Missing Number\nGiven an array `nums` containing `n` distinct numbers in the range `[0, n]`, return the only number in the range that is missing.\n\n**Test Cases**\n1. Input: nums = [3, 0, 1]\n   Output: 2\n   Explanation: n = 3, range is [0, 3], missing 2.\n2. Input: nums = [0, 1]\n   Output: 2\n3. Input: nums = [9, 6, 4, 2, 3, 5, 7, 0, 1]\n   Output: 8\n\n**Constraints & Requirements:**\n- n == nums.length, 1 <= n <= 10^4\n- Solve in $O(N)$ time and $O(1)$ extra space using Gauss sum or XOR.",
            "### Problem: Combinations\nGiven two integers `n` and `k`, return all possible combinations of `k` numbers chosen from the range `[1, n]`.\n\n**Test Cases**\n1. Input: n = 4, k = 2\n   Output: [[1, 2], [1, 3], [1, 4], [2, 3], [2, 4], [3, 4]]\n   Explanation: All size-2 combinations from 1 to 4.\n2. Input: n = 1, k = 1\n   Output: [[1]]\n\n**Constraints & Requirements:**\n- 1 <= n <= 20, 1 <= k <= n\n- Implement using backtracking pruning.",
            "### Problem: Diameter of Binary Tree\nGiven the `root` of a binary tree, return the length of the diameter of the tree (longest path between any two nodes).\n\n**Test Cases**\n1. Input: root = [1, 2, 3, 4, 5]\n   Output: 3\n   Explanation: Length of path [4, 2, 1, 3] or [5, 2, 1, 3].\n2. Input: root = [1, 2]\n   Output: 1\n\n**Constraints & Requirements:**\n- The number of nodes in tree is in range [1, 10^4].\n- Compute in single DFS pass in $O(N)$ time.",
            "### Problem: Meeting Rooms\nGiven an array of meeting time intervals where `intervals[i] = [start_i, end_i]`, determine if a person could attend all meetings without overlap.\n\n**Test Cases**\n1. Input: intervals = [[0, 30], [5, 10], [15, 20]]\n   Output: false\n   Explanation: [0, 30] overlaps with [5, 10] and [15, 20].\n2. Input: intervals = [[7, 10], [2, 4]]\n   Output: true\n\n**Constraints & Requirements:**\n- 0 <= intervals.length <= 10^4\n- Sort intervals by start time in $O(N \\log N)$."
        ],
        "Medium": [
            "### Problem: Range Increment Queries\nGiven length `n` and a 2D array of update operations where `operations[i] = [startIndex, endIndex, inc]`, start with an array of zeros of length `n` and apply all increment operations on range `[startIndex, endIndex]` (inclusive). Return the final modified array.\n\n**Test Cases**\n1. Input: n = 5, operations = [[1, 3, 2], [2, 4, 3]]\n   Output: [0, 2, 5, 5, 3]\n   Explanation: Start with [0,0,0,0,0]. After operation 1: [0,2,2,2,0]. After operation 2: [0,2,5,5,3].\n2. Input: n = 3, operations = [[0, 2, 1]]\n   Output: [1, 1, 1]\n   Explanation: Increment entire array of size 3 by 1.\n3. Input: n = 4, operations = [[0, 1, 3], [1, 3, 2]]\n   Output: [3, 5, 2, 2]\n\n**Constraints & Requirements:**\n- 1 <= n <= 10^5\n- 0 <= operations.length <= 10^4\n- Optimize to $O(n + m)$ using Difference Array Prefix Sums instead of naive $O(n \\times m)$.",
            "### Problem: Longest Substring Without Repeating Characters\nGiven a string `s`, find the length of the longest substring without duplicate characters.\n\n**Test Cases**\n1. Input: s = \"abcabcbb\"\n   Output: 3\n   Explanation: The answer is \"abc\", with the length of 3.\n2. Input: s = \"bbbbb\"\n   Output: 1\n   Explanation: The answer is \"b\", with the length of 1.\n3. Input: s = \"pwwkew\"\n   Output: 3\n   Explanation: The answer is \"wke\", with length of 3.\n\n**Constraints & Requirements:**\n- 0 <= s.length <= 5 * 10^4\n- Solve in $O(N)$ time with sliding window and hash map.",
            "### Problem: 3Sum\nGiven an integer array `nums`, return all the triplets `[nums[i], nums[j], nums[k]]` such that `i != j`, `i != k`, and `j != k`, and `nums[i] + nums[j] + nums[k] == 0`.\n\n**Test Cases**\n1. Input: nums = [-1, 0, 1, 2, -1, -4]\n   Output: [[-1, -1, 2], [-1, 0, 1]]\n   Explanation: Distinct triplets that sum to 0.\n2. Input: nums = [0, 1, 1]\n   Output: []\n3. Input: nums = [0, 0, 0]\n   Output: [[0, 0, 0]]\n\n**Constraints & Requirements:**\n- 3 <= nums.length <= 3000\n- Sort and use two pointers to solve in $O(N^2)$ time with duplicate avoidance.",
            "### Problem: Product of Array Except Self\nGiven an integer array `nums`, return an array `answer` such that `answer[i]` is equal to the product of all elements of `nums` except `nums[i]` without using division.\n\n**Test Cases**\n1. Input: nums = [1, 2, 3, 4]\n   Output: [24, 12, 8, 6]\n   Explanation: Left prefix products multiplied by right suffix products.\n2. Input: nums = [-1, 1, 0, -3, 3]\n   Output: [0, 0, 9, 0, 0]\n\n**Constraints & Requirements:**\n- 2 <= nums.length <= 10^5\n- Must run in $O(N)$ time and $O(1)$ extra space.",
            "### Problem: Coin Change\nYou are given an integer array `coins` representing coins of different denominations and an integer `amount`. Return the fewest number of coins that you need to make up that amount, or `-1`.\n\n**Test Cases**\n1. Input: coins = [1, 2, 5], amount = 11\n   Output: 3\n   Explanation: 11 = 5 + 5 + 1 (3 coins).\n2. Input: coins = [2], amount = 3\n   Output: -1\n3. Input: coins = [1], amount = 0\n   Output: 0\n\n**Constraints & Requirements:**\n- 1 <= coins.length <= 12, 0 <= amount <= 10^4\n- Use bottom-up DP in $O(\\text{amount} \\times \\text{len})$ time.",
            "### Problem: Course Schedule\nThere are a total of `numCourses` courses you have to take, labeled from 0 to `numCourses - 1`. You are given `prerequisites` where `prerequisites[i] = [a, b]` means you must take `b` before `a`. Return `true` if you can finish all courses.\n\n**Test Cases**\n1. Input: numCourses = 2, prerequisites = [[1, 0]]\n   Output: true\n   Explanation: Take course 0 then 1.\n2. Input: numCourses = 2, prerequisites = [[1, 0], [0, 1]]\n   Output: false\n   Explanation: Directed cycle detected.\n3. Input: numCourses = 4, prerequisites = [[1, 0], [2, 1], [3, 2]]\n   Output: true\n\n**Constraints & Requirements:**\n- 1 <= numCourses <= 2000\n- Cycle detection via Kahn's BFS or DFS coloring in $O(V + E)$ time.",
            "### Problem: Number of Islands\nGiven an `m x n` 2D binary grid `grid` which represents a map of `'1'`s (land) and `'0'`s (water), return the number of islands.\n\n**Test Cases**\n1. Input: grid = [[\"1\",\"1\",\"1\",\"1\",\"0\"],[\"1\",\"1\",\"0\",\"1\",\"0\"],[\"1\",\"1\",\"0\",\"0\",\"0\"],[\"0\",\"0\",\"0\",\"0\",\"0\"]\n   Output: 1\n   Explanation: All connected land cells form 1 island.\n2. Input: grid = [[\"1\",\"1\",\"0\",\"0\",\"0\"],[\"1\",\"1\",\"0\",\"0\",\"0\"],[\"0\",\"0\",\"1\",\"0\",\"0\"],[\"0\",\"0\",\"0\",\"1\",\"1\"]\n   Output: 3\n\n**Constraints & Requirements:**\n- m == grid.length, n == grid[i].length, 1 <= m, n <= 300\n- BFS/DFS connected components in $O(M \\times N)$ time.",
            "### Problem: Group Anagrams\nGiven an array of strings `strs`, group the anagrams together. You can return the answer in any order.\n\n**Test Cases**\n1. Input: strs = [\"eat\", \"tea\", \"tan\", \"ate\", \"nat\", \"bat\"]\n   Output: [[\"bat\"], [\"nat\", \"tan\"], [\"ate\", \"eat\", \"tea\"]]\n   Explanation: Words sharing the same sorted key are grouped.\n2. Input: strs = [\"\"]\n   Output: [[\"\"]]\n\n**Constraints & Requirements:**\n- 1 <= strs.length <= 10^4\n- Hash by character frequency count tuple or sorted string in $O(N \\cdot K)$.",
            "### Problem: Kth Largest Element in an Array\nGiven an integer array `nums` and an integer `k`, return the `k`th largest element in the array.\n\n**Test Cases**\n1. Input: nums = [3, 2, 1, 5, 6, 4], k = 2\n   Output: 5\n   Explanation: Sorted descending: [6, 5, 4, 3, 2, 1], 2nd largest is 5.\n2. Input: nums = [3, 2, 3, 1, 2, 4, 5, 5, 6], k = 4\n   Output: 4\n\n**Constraints & Requirements:**\n- 1 <= k <= nums.length <= 10^5\n- QuickSelect ($O(N)$ average) or Min-Heap ($O(N \\log K)$).",
            "### Problem: Word Break\nGiven a string `s` and a dictionary of strings `wordDict`, return `true` if `s` can be segmented into a space-separated sequence of one or more dictionary words.\n\n**Test Cases**\n1. Input: s = \"leetcode\", wordDict = [\"leet\", \"code\"]\n   Output: true\n   Explanation: \"leetcode\" can be segmented as \"leet code\".\n2. Input: s = \"applepenapple\", wordDict = [\"apple\", \"pen\"]\n   Output: true\n3. Input: s = \"catsandog\", wordDict = [\"cats\", \"dog\", \"sand\", \"and\", \"cat\"]\n   Output: false\n\n**Constraints & Requirements:**\n- 1 <= s.length <= 300, 1 <= wordDict.length <= 1000\n- Dynamic programming `dp[i]` tracking valid prefixes in $O(N^2)$ time.",
            "### Problem: Daily Temperatures\nGiven an array of integers `temperatures` represents daily temperatures, return an array `answer` such that `answer[i]` is the number of days you have to wait after the $i^{\\text{th}}$ day to get a warmer temperature.\n\n**Test Cases**\n1. Input: temperatures = [73, 74, 75, 71, 69, 72, 76, 73]\n   Output: [1, 1, 4, 2, 1, 1, 0, 0]\n   Explanation: Monotonic decreasing stack indices.\n2. Input: temperatures = [30, 40, 50, 60]\n   Output: [1, 1, 1, 0]\n\n**Constraints & Requirements:**\n- 1 <= temperatures.length <= 10^5\n- Monotonic Decreasing Stack in $O(N)$ time and $O(N)$ space.",
            "### Problem: Permutations\nGiven an array `nums` of distinct integers, return all the possible permutations. You can return the answer in any order.\n\n**Test Cases**\n1. Input: nums = [1, 2, 3]\n   Output: [[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]\n   Explanation: All 3! = 6 permutations.\n2. Input: nums = [0, 1]\n   Output: [[0, 1], [1, 0]]\n\n**Constraints & Requirements:**\n- 1 <= nums.length <= 6\n- Backtracking in $O(N \\times N!)$ time.",
            "### Problem: Subarray Sum Equals K\nGiven an array of integers `nums` and an integer `k`, return the total number of subarrays whose sum equals to `k`.\n\n**Test Cases**\n1. Input: nums = [1, 1, 1], k = 2\n   Output: 2\n   Explanation: Subarrays [1, 1] at indices [0, 1] and [1, 2].\n2. Input: nums = [1, 2, 3], k = 3\n   Output: 2\n\n**Constraints & Requirements:**\n- 1 <= nums.length <= 2 * 10^4\n- Prefix sum frequency hash map in $O(N)$ time and $O(N)$ space.",
            "### Problem: Search in Rotated Sorted Array\nGiven the array `nums` after the possible rotation and an integer `target`, return the index of `target` if it is in `nums`, or `-1` if it is not in `nums`.\n\n**Test Cases**\n1. Input: nums = [4, 5, 6, 7, 0, 1, 2], target = 0\n   Output: 4\n   Explanation: 0 is at index 4.\n2. Input: nums = [4, 5, 6, 7, 0, 1, 2], target = 3\n   Output: -1\n\n**Constraints & Requirements:**\n- 1 <= nums.length <= 5000\n- Binary search in $O(\\log N)$ time comparing `nums[mid]` against `nums[left]`.",
            "### Problem: Top K Frequent Elements\nGiven an integer array `nums` and an integer `k`, return the `k` most frequent elements.\n\n**Test Cases**\n1. Input: nums = [1, 1, 1, 2, 2, 3], k = 2\n   Output: [1, 2]\n   Explanation: 1 appears 3 times, 2 appears 2 times.\n2. Input: nums = [1], k = 1\n   Output: [1]\n\n**Constraints & Requirements:**\n- 1 <= nums.length <= 10^5, k in range [1, unique elements]\n- Bucket Sort in $O(N)$ time or min-heap in $O(N \\log K)$ time.",
            "### Problem: Container With Most Water\nYou are given an integer array `height` of length `n`. Find two lines that together with the x-axis form a container, such that the container contains the most water. Return the maximum amount of water a container can store.\n\n**Test Cases**\n1. Input: height = [1, 8, 6, 2, 5, 4, 8, 3, 7]\n   Output: 49\n   Explanation: Max area between indices 1 and 8 (height 7 * width 7 = 49).\n2. Input: height = [1, 1]\n   Output: 1\n\n**Constraints & Requirements:**\n- n == height.length, 2 <= n <= 10^5\n- Two-pointer greedy inward convergence in $O(N)$ time and $O(1)$ space.",
            "### Problem: Subsets\nGiven an integer array `nums` of unique elements, return all possible subsets (the power set).\n\n**Test Cases**\n1. Input: nums = [1, 2, 3]\n   Output: [[], [1], [2], [1, 2], [3], [1, 3], [2, 3], [1, 2, 3]]\n   Explanation: The power set of size 2^3 = 8.\n2. Input: nums = [0]\n   Output: [[], [0]]\n\n**Constraints & Requirements:**\n- 1 <= nums.length <= 10\n- Backtracking or cascade generation in $O(N \\times 2^N)$ time.",
            "### Problem: House Robber\nYou are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed, the only constraint stopping you from robbing each of them is that adjacent houses have security systems connected. Return the maximum amount of money you can rob tonight without alerting the police.\n\n**Test Cases**\n1. Input: nums = [1, 2, 3, 1]\n   Output: 4\n   Explanation: Rob house 1 (money = 1) and house 3 (money = 3), total = 4.\n2. Input: nums = [2, 7, 9, 3, 1]\n   Output: 12\n   Explanation: Rob houses 1, 3, and 5 (2 + 9 + 1 = 12).\n\n**Constraints & Requirements:**\n- 1 <= nums.length <= 100\n- Solve in $O(N)$ time and $O(1)$ space using two variables.",
            "### Problem: Longest Consecutive Sequence\nGiven an unsorted array of integers `nums`, return the length of the longest consecutive elements sequence.\n\n**Test Cases**\n1. Input: nums = [100, 4, 200, 1, 3, 2]\n   Output: 4\n   Explanation: The longest consecutive sequence is [1, 2, 3, 4], length 4.\n2. Input: nums = [0, 3, 7, 2, 5, 8, 4, 6, 0, 1]\n   Output: 9\n\n**Constraints & Requirements:**\n- 0 <= nums.length <= 10^5\n- Must run in $O(N)$ time using a Hash Set by checking if `num - 1` exists.",
            "### Problem: Merge Intervals\nGiven an array of `intervals` where `intervals[i] = [start_i, end_i]`, merge all overlapping intervals, and return an array of the non-overlapping intervals that cover all the intervals in the input.\n\n**Test Cases**\n1. Input: intervals = [[1, 3], [2, 6], [8, 10], [15, 18]]\n   Output: [[1, 6], [8, 10], [15, 18]]\n   Explanation: [1, 3] and [2, 6] overlap, merging into [1, 6].\n2. Input: intervals = [[1, 4], [4, 5]]\n   Output: [[1, 5]]\n\n**Constraints & Requirements:**\n- 1 <= intervals.length <= 10^4\n- Sort intervals by start time and merge in $O(N \\log N)$ time."
        ],
        "Hard": [
            "### Problem: Trapping Rain Water\nGiven `n` non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.\n\n**Test Cases**\n1. Input: height = [0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]\n   Output: 6\n   Explanation: The elevation map traps 6 units of rain water.\n2. Input: height = [4, 2, 0, 3, 2, 5]\n   Output: 9\n\n**Constraints & Requirements:**\n- n == height.length, 1 <= n <= 2 * 10^4\n- Solve in $O(N)$ time and $O(1)$ auxiliary space with two pointers.",
            "### Problem: Sliding Window Maximum\nYou are given an array of integers `nums`, there is a sliding window of size `k` which is moving from the very left of the array to the very right. Return the max sliding window.\n\n**Test Cases**\n1. Input: nums = [1, 3, -1, -3, 5, 3, 6, 7], k = 3\n   Output: [3, 3, 5, 5, 6, 7]\n   Explanation: Sliding window max values at each step.\n2. Input: nums = [1], k = 1\n   Output: [1]\n\n**Constraints & Requirements:**\n- 1 <= nums.length <= 10^5, 1 <= k <= nums.length\n- Monotonic decreasing deque in amortized $O(N)$ time and $O(K)$ space.",
            "### Problem: Minimum Window Substring\nGiven two strings `s` and `t` of lengths `m` and `n` respectively, return the minimum window substring of `s` such that every character in `t` (including duplicates) is included in the window. If there is no such substring, return the empty string `\"\"`.\n\n**Test Cases**\n1. Input: s = \"ADOBECODEBANC\", t = \"ABC\"\n   Output: \"BANC\"\n   Explanation: The minimum window substring \"BANC\" includes 'A', 'B', and 'C' from string t.\n2. Input: s = \"a\", t = \"a\"\n   Output: \"a\"\n3. Input: s = \"a\", t = \"aa\"\n   Output: \"\"\n\n**Constraints & Requirements:**\n- 1 <= s.length, t.length <= 10^5\n- Sliding window with character frequency counter in $O(M + N)$ time.",
            "### Problem: First Missing Positive\nGiven an unsorted integer array `nums`, return the smallest positive integer that is not present in `nums`.\n\n**Test Cases**\n1. Input: nums = [1, 2, 0]\n   Output: 3\n   Explanation: Numbers in the range [1,2] are present, so 3 is missing.\n2. Input: nums = [3, 4, -1, 1]\n   Output: 2\n3. Input: nums = [7, 8, 9, 11, 12]\n   Output: 1\n\n**Constraints & Requirements:**\n- 1 <= nums.length <= 10^5\n- Must run in $O(N)$ time and $O(1)$ auxiliary space using in-place bucket indexing.",
            "### Problem: Edit Distance\nGiven two strings `word1` and `word2`, return the minimum number of operations required to convert `word1` to `word2` (insert, delete, or replace a character).\n\n**Test Cases**\n1. Input: word1 = \"horse\", word2 = \"ros\"\n   Output: 3\n   Explanation: horse -> rorse (replace 'h' with 'r') -> rose (remove 'r') -> ros (remove 'e').\n2. Input: word1 = \"intention\", word2 = \"execution\"\n   Output: 5\n\n**Constraints & Requirements:**\n- 0 <= word1.length, word2.length <= 500\n- 2D Dynamic Programming in $O(M \\times N)$ time.",
            "### Problem: Jump Game\nYou are given an integer array `nums`. You are initially positioned at the array's first index, and each element in the array represents your maximum jump length at that position. Return `true` if you can reach the last index, or `false` otherwise.\n\n**Test Cases**\n1. Input: nums = [2, 3, 1, 1, 4]\n   Output: true\n   Explanation: Jump 1 step from index 0 to 1, then 3 steps to the last index.\n2. Input: nums = [3, 2, 1, 0, 4]\n   Output: false\n\n**Constraints & Requirements:**\n- 1 <= nums.length <= 10^4\n- Greedy maximum reach tracking in $O(N)$ time and $O(1)$ space."
        ]
    },
    "machine learning": {
        "Easy": [
            "Can you explain the fundamental difference between supervised, unsupervised, and reinforcement learning with real-world examples?",
            "What is the bias-variance tradeoff, and how does model complexity directly influence underfitting vs overfitting?",
            "What is the mathematical difference between L1 (Lasso) and L2 (Ridge) regularization, and why does L1 lead to sparse feature selection?",
            "Explain precision, recall, and F1-score. When would you optimize strictly for recall over precision?",
            "Can you walk me through how gradient descent iteratively minimizes a model's loss function?",
            "What is the role of activation functions in neural networks, and why is ReLU preferred over Sigmoid in hidden layers?",
            "Explain cross-validation (K-Fold) and why evaluating solely on a single train-test split can lead to overly optimistic metrics.",
            "What is the difference between classification and regression, and what loss functions are standard for each?",
            "How does logistic regression map unbounded linear outputs to probabilities between 0 and 1 using the sigmoid function?",
            "What is the curse of dimensionality, and how does increasing feature count affect distance metrics in algorithms like KNN?",
            "Explain the difference between parametric and non-parametric machine learning models with examples.",
            "What is data leakage, and how does standardizing features before performing train-test splitting cause leakage?",
            "How does a Decision Tree decide where to split a node (Gini Impurity vs Information Gain / Entropy)?",
            "What is the Receiver Operating Characteristic (ROC) curve, and how is Area Under the Curve (AUC) interpreted?",
            "Explain the difference between covariance and correlation, and why correlation is normalized between -1 and 1.",
            "What is one-hot encoding vs target encoding, and when would one-hot encoding lead to excessive sparsity?",
            "How do outliers impact Mean Squared Error (MSE) compared to Mean Absolute Error (MAE)?",
            "What is the purpose of a validation set distinct from both training and test sets?",
            "Explain the concept of learning rate in optimization: what happens when it is too high versus too low?",
            "What is early stopping in model training, and how does tracking validation loss prevent overfitting?"
        ],
        "Medium": [
            "In a real-time credit card fraud detection dataset where fraudulent transactions make up only 0.1% of samples, what sampling techniques and evaluation metrics would you use?",
            "Explain the core differences between bagging and boosting, specifically comparing Random Forests with Gradient Boosted Decision Trees (XGBoost/LightGBM).",
            "Walk me through the architectural and mathematical difference between Batch Normalization and Layer Normalization. Why is LayerNorm standard in Transformers?",
            "How do you detect and prevent target leakage in a multi-stage time-series feature engineering pipeline?",
            "If training loss is consistently decreasing but validation loss diverges after epoch 12, what concrete diagnostic steps and remedies would you apply?",
            "How does the self-attention mechanism in Transformers compute attention weights mathematically ($Q, K, V$ matrices and $\\text{softmax}(QK^T / \\sqrt{d_k})$)?",
            "Compare Word2Vec embeddings (Skip-gram / CBOW) with contextual Transformer embeddings (BERT). How do they handle polysemy?",
            "Explain the Vanishing and Exploding Gradient problem in deep networks. What mathematical mechanisms in LSTMs and ResNet skip connections mitigate it?",
            "How would you evaluate and calibrate a machine learning model whose predicted probabilities are poorly calibrated (Platt scaling vs Isotonic regression)?",
            "Describe the mathematical mechanics of Principal Component Analysis (PCA) through eigendecomposition / SVD of the covariance matrix.",
            "When building an ML recommendation system, how do you solve the cold start problem for newly onboarded users and items?",
            "What is the mathematical formulation of Focal Loss, and why does down-weighting easy examples improve object detection / class imbalance?",
            "Compare Stochastic Gradient Descent (SGD) with momentum against adaptive optimizers like Adam and RMSprop.",
            "How do you handle covariate shift and concept drift in a production ML model serving real-time predictions?",
            "Explain Dropout regularization during training versus inference: why must activations be scaled by $1 - p$ during evaluation?",
            "How would you structure a multi-task learning architecture where a single backbone shares representations across two distinct prediction heads?",
            "What is the difference between generative and discriminative modeling, contrasting Naive Bayes with Logistic Regression?",
            "How do you perform hyperparameter tuning efficiently at scale (Random Search vs Bayesian Optimization with Gaussian Processes)?",
            "Explain K-Means clustering convergence criteria, the elbow method, and how K-Means++ initialization avoids suboptimal local minima.",
            "In natural language processing, how does Byte-Pair Encoding (BPE) tokenize out-of-vocabulary words into subwords?"
        ],
        "Hard": [
            "Analyze the memory bandwidth, IO-awareness, and computational efficiency improvements of FlashAttention compared to standard multi-head attention.",
            "How would you design a real-time recommendation engine serving 50,000 queries per second with sub-40ms latency, balancing two-stage retrieval (ANN/embeddings) and ranking?",
            "Compare fine-tuning strategies for Large Language Models: Full fine-tuning vs LoRA vs QLoRA vs Prefix Tuning, analyzing GPU VRAM, parameter efficiency, and catastrophic forgetting.",
            "How would you architect a distributed model training cluster across multi-node GPU instances, comparing Data Parallelism (DDP), Fully Sharded Data Parallel (FSDP), and Tensor Parallelism?",
            "Design an automated ML observability pipeline to monitor covariate shift and concept drift on high-velocity production data streams.",
            "Walk through Direct Preference Optimization (DPO) vs Reinforcement Learning from Human Feedback (RLHF with PPO) for aligning foundation language models.",
            "How does Rotary Position Embedding (RoPE) encode relative position information mathematically into query and key representations?",
            "Design a vector search similarity engine indexing 1 billion 768-dimensional embeddings with sub-10ms recall, comparing HNSW, IVF-PQ, and ScaNN.",
            "Explain KV-Cache optimization in LLM text generation: how does PagedAttention eliminate memory fragmentation in vLLM serving engines?",
            "How would you train a diffusion model (DDPM / DDIM) for image generation, explaining the forward noise schedule, score matching, and reverse denoising U-Net?",
            "Analyze speculative decoding in Large Language Models: how does a smaller draft model accelerate token generation without changing target distribution?",
            "How would you detect and remediate adversarial attacks (FGSM, PGD) designed to perturb image classifiers or LLM jailbreaks?",
            "Design a real-time feature store (like Feast / Hopsworks) that guarantees point-in-time correctness for training and sub-5ms low-latency feature retrieval for inference.",
            "Explain Mixture of Experts (MoE) routing mechanisms (Top-K gating, load balancing auxiliary loss) in models like Mixtral.",
            "How does Grouped-Query Attention (GQA) reduce memory bandwidth during LLM decoding compared to Multi-Head Attention and Multi-Query Attention?",
            "Walk through contrastive representation learning in CLIP (InfoNCE loss formulation) and how cross-modal temperature parameter modulates gradients.",
            "How would you benchmark and quantize a 70B parameter model from FP16 to INT4 (AWQ vs GPTQ) while preserving perplexity on complex reasoning benchmarks?",
            "Design an end-to-end continuous retraining pipeline with automated canary evaluation, shadow deployment, and automated rollback upon metric regression.",
            "Explain the mathematical formulation of Neural ODEs and how adjoint sensitivity method allows backpropagation through ODE solvers with $O(1)$ memory.",
            "How do you implement distributed asynchronous parameter servers for trillion-parameter sparse embedding tables in click-through rate (CTR) prediction?"
        ]
    },
    "system design": {
        "Easy": [
            "What is the core difference between horizontal scaling and vertical scaling, and what are their respective limits?",
            "Can you explain the CAP theorem and why distributed networks must choose between Consistency and Availability during network partitions?",
            "What is the difference between relational SQL databases and NoSQL databases, and what are common NoSQL data models?",
            "What is a reverse proxy (e.g., Nginx, Envoy) and what critical advantages does it provide in modern web architectures?",
            "How does DNS resolution translate a domain name into an IP address from browser cache to authoritative name servers?",
            "What is a Content Delivery Network (CDN), and how does edge caching reduce latency for static assets?",
            "Explain the difference between synchronous HTTP communication and asynchronous message passing with message queues.",
            "What is database replication (Leader-Follower), and how does read-scaling work across follower nodes?",
            "What is a Load Balancer, and what are common routing algorithms (Round Robin, Least Connections, IP Hash)?",
            "Explain database indexing using B-Trees: why does an index accelerate read queries while adding latency to write operations?",
            "What is caching, and how does the Cache-Aside pattern work in conjunction with an application server?",
            "What is the difference between stateless and stateful service architectures, and why are stateless servers easier to scale horizontally?",
            "What is database connection pooling, and why is creating a fresh TCP connection per request a bottleneck?",
            "Explain the difference between REST, GraphQL, and gRPC for client-server communication.",
            "What is an API Gateway, and what responsibilities does it consolidate (rate limiting, authentication, SSL termination)?",
            "What is database sharding (horizontal partitioning), and what is a shard key?",
            "Explain what a single point of failure (SPOF) is and how redundancy eliminates it.",
            "What is the difference between throughput (QPS / RPS) and latency (p50, p95, p99)?",
            "What is data serialization (JSON vs Protocol Buffers vs Avro), and how does binary serialization save network bandwidth?",
            "Explain polling vs Long-Polling vs WebSockets vs Server-Sent Events (SSE) for real-time web applications."
        ],
        "Medium": [
            "Design a URL shortening service like bit.ly capable of handling 20,000 writes/sec and 200,000 reads/sec. How do you generate unique IDs and guarantee low-latency redirects?",
            "Explain how consistent hashing works and how virtual nodes prevent hot-spotting when cache nodes are added or removed dynamically.",
            "How would you implement a distributed API rate limiter supporting 100,000 req/sec using Redis? Which algorithm (token bucket, sliding window counter) would you pick and why?",
            "Describe caching strategies (Cache-Aside, Write-Through, Write-Behind) for an e-commerce catalog, and explain how to mitigate cache stampedes (thundering herd).",
            "How does Apache Kafka guarantee message ordering, and what trade-offs exist between partition count, consumer concurrency, and strict FIFO delivery?",
            "Design a distributed unique ID generator producing 64-bit strictly monotonic IDs (like Twitter Snowflake).",
            "Architect a notification service delivering push, SMS, and email notifications to 50 million users daily with rate limits and delivery prioritization.",
            "Design an e-commerce flash sale system handling 100,000 users attempting to buy 1,000 inventory items simultaneously without overselling.",
            "How do you implement distributed transactions across microservices using the Saga pattern (Choreography vs Orchestration)?",
            "Design an image and video upload processing pipeline with thumbnail generation, deduplication, and secure S3 presigned URLs.",
            "Compare relational ACID transactions with BASE (Basically Available, Soft state, Eventual consistency) distributed models.",
            "Design a Web Crawler capable of crawling 100 million web pages weekly while respecting robots.txt and handling domain politeness.",
            "How do database isolation levels (Read Committed, Repeatable Read, Serializable) prevent dirty reads, non-repeatable reads, and phantom reads?",
            "Design a Pastebin service allowing users to store and share text snippets with customizable expiration TTLs and access analytics.",
            "How does a distributed cache cluster handle cache invalidation and cache penetration with Bloom filters?",
            "Design a metrics collection and monitoring system (like Prometheus) storing time-series data with downsampling and alerting.",
            "Explain the difference between Optimistic Concurrency Control (version checking) and Pessimistic Locking in database transactions.",
            "Design a key-value store with read repair, hinted handoff, and tunable consistency levels (Cassandra model).",
            "How do you architect a secure multi-tenant SaaS database (separate database per tenant vs shared database with tenant ID column)?",
            "Design a top-K trending topics service that computes most frequent hashtags in real-time over a sliding 1-hour window."
        ],
        "Hard": [
            "Architect a real-time collaborative document editing system (like Google Docs) supporting concurrent offline and online edits. Compare Operational Transformation (OT) vs CRDTs.",
            "Design a globally distributed payment transaction ledger ensuring strict ACID compliance, idempotency, and multi-region disaster recovery.",
            "How would you design an event-driven stream processing platform handling 2 million events per second with exactly-once processing semantics under worker node crashes?",
            "Design a multi-region active-active database architecture with conflict resolution for a mission-critical banking application with RPO < 1s and RTO < 30s.",
            "How would you architect a distributed search and log analytics engine across petabytes of data with sub-second query latency?",
            "Design a distributed message broker from scratch: Explain commit log storage layout, zero-copy OS transfers (`sendfile`), and consumer offset checkpointing.",
            "How do distributed consensus algorithms (Raft vs Paxos) achieve leader election, log replication, and safe recovery during network splits?",
            "Design a global video streaming platform (like Netflix) with adaptive bitrate transcoding, dynamic CDN edge steering, and edge session tokens.",
            "Architect a real-time ride-sharing dispatch system (like Uber) handling location updates from 2 million active drivers and matching riders in under 20ms.",
            "Design a distributed database query engine (like Presto/Trino) executing federated SQL queries across heterogeneous distributed data sources.",
            "How would you architect a zero-downtime database migration strategy from a legacy Oracle monolith to a distributed CockroachDB cluster with zero data loss?",
            "Design a distributed lock manager (like Redlock / Google Chubby / ZooKeeper) and prove safety guarantees under asynchronous network delays and GC pauses.",
            "Architect an ad-click aggregation and real-time fraud detection pipeline processing 500,000 clicks/sec with micro-batch windowing and deduplication.",
            "Design a distributed file system (like Google GFS / HDFS) addressing master bottleneck, chunk replication, heartbeat monitoring, and split-brain resolution.",
            "How would you design a global content recommendation feed serving 200 million daily active users with personalization, deduplication, and diversity reranking?",
            "Architect an enterprise disaster recovery architecture: compare active-passive with pilot light vs active-active multi-cloud deployment.",
            "Design a real-time multiplayer gaming server architecture handling synchronization, dead reckoning interpolation, and UDP packet loss.",
            "How do you implement distributed tracing (OpenTelemetry / Jaeger) across 5,000 microservices without degrading network throughput or storage budgets?",
            "Design an automated database auto-sharding and rebalancing engine that splits and migrates partitions without dropping active client connections.",
            "Architect a high-frequency trading (HFT) matching engine with sub-microsecond order execution, deterministic order book matching, and audit logging."
        ]
    },
    "python": {
        "Easy": [
            "Can you explain the difference between a list and a tuple in Python, particularly regarding mutability and memory allocation?",
            "What is the Global Interpreter Lock (GIL) in CPython and how does it impact multi-threaded CPU-bound programs?",
            "How do Python dictionaries handle key collisions under the hood, and what are the requirements for an object to be used as a dictionary key?",
            "What is the difference between shallow copy (`copy.copy`) and deep copy (`copy.deepcopy`) in Python?",
            "How does Python manage memory and clean up unused objects? Can you explain reference counting and cyclic garbage collection?",
            "What are Python list comprehensions, and why are they generally faster than standard for-loops with `.append()`?",
            "Explain the difference between `is` and `==` in Python with examples (including integer caching).",
            "What are `*args` and `**kwargs` in Python function definitions, and how does argument unpacking work?",
            "What is the purpose of `__init__` and `self` in Python class definitions?",
            "Explain how the `with` statement and context managers work using `__enter__` and `__exit__`.",
            "What is the difference between `range()` and a list in Python 3 in terms of memory efficiency?",
            "How does Python handle exceptions with `try`, `except`, `else`, and `finally` blocks?",
            "What are lambda functions in Python, and what are their limitations compared to standard `def` functions?",
            "Explain the difference between static methods (`@staticmethod`), class methods (`@classmethod`), and instance methods.",
            "What are Python sets, how are they implemented under the hood, and what are their lookup time bounds?",
            "What is string immutability in Python, and why is repeated `+` string concatenation in a loop an antipattern?",
            "How do Python modules and packages work, and what is the role of `__init__.py`?",
            "Explain the built-in functions `zip()`, `map()`, and `filter()` with practical examples.",
            "What is the difference between `append()` and `extend()` on Python lists?",
            "What is duck typing in Python, and what does the phrase 'Easier to ask for forgiveness than permission' (EAFP) mean?"
        ],
        "Medium": [
            "How would you implement a custom function decorator with arguments in Python that logs execution time in milliseconds?",
            "Explain how Python generators and the `yield` keyword work. In what production scenario would you prefer a generator over a list comprehension?",
            "When designing high-throughput I/O tasks in Python, how do you decide between `asyncio`, `multiprocessing`, and `concurrent.futures.ThreadPoolExecutor`?",
            "How does Python resolve multiple inheritance method calls (Method Resolution Order / C3 Linearization)?",
            "How would you process a 15GB CSV file in Python on a worker machine constrained to 2GB of RAM without crashing?",
            "Explain Python descriptors (`__get__`, `__set__`, `__delete__`) and how `@property` is built on top of the descriptor protocol.",
            "What are metaclasses in Python (`type`), and how do frameworks like Pydantic or Django ORM use metaclasses to inspect class definitions?",
            "How does `asyncio` event loop execute tasks concurrently on a single thread? What is the difference between `asyncio.gather` and `asyncio.wait`?",
            "Explain how Python's `collections.defaultdict`, `Counter`, and `deque` optimize standard data workflows.",
            "How do `__slots__` optimize memory in Python classes with millions of instantiated objects?",
            "What is the difference between `pickle` and `json` serialization in Python, and what are the security vulnerabilities of unpickling untrusted data?",
            "How would you write a custom context manager in Python using the `@contextlib.contextmanager` decorator?",
            "Explain monkey patching in Python: how does it work, when is it useful for testing, and what risks does it introduce in production?",
            "How does CPython optimize small integers (-5 to 256) and string interning?",
            "Explain the difference between `threading.Lock` and `threading.RLock` (reentrant lock) in Python.",
            "How would you implement an LRU cache decorator from scratch in Python without using `functools.lru_cache`?",
            "What is the purpose of the `weakref` module in Python, and how does it prevent circular reference memory leaks?",
            "How do type hints and the `typing` module (Generics, Union, Protocol) integrate with static type checkers like `mypy`?",
            "Explain the difference between `os.fork()`, `multiprocessing.Process`, and `subprocess.Popen` in Unix environments.",
            "How do abstract base classes (`abc.ABC` and `@abstractmethod`) enforce interface contracts in Python?"
        ],
        "Hard": [
            "Explain the low-level memory allocation hierarchy of CPython (arenas, pools, blocks) and how small object allocation (`PyObject_Malloc`) avoids system malloc overhead.",
            "If you were architecting a distributed asynchronous task queue like Celery from scratch in Python, how would you handle worker heartbeats, acknowledgment guarantees, and prefetch limits?",
            "Analyze the trade-offs of using `asyncio` event loops vs thread pools when integrating legacy synchronous database drivers with an asynchronous web framework like FastAPI.",
            "How would you design a hot-reloading plugin system in Python that dynamically imports modules without memory leaks or namespace contamination?",
            "Compare the performance characteristics and execution models of CPython vs PyPy vs Cython for CPU-bound computational workloads.",
            "How would you profile CPU bottlenecks and memory leaks in a live Python production service using `py-spy`, `cProfile`, and `tracemalloc`?",
            "Explain the internal implementation of Python dictionary lookup in CPython 3.6+ (compact dict structure separating hash table entries from key-value pairs).",
            "How does the sub-interpreter model (PEP 554 / PEP 684 per-interpreter GIL) provide multi-core concurrency in Python 3.12+?",
            "How would you write a C-extension for Python using the Python C-API to accelerate a matrix multiplication algorithm by 50x?",
            "Explain how Python bytecode is generated, compiled, and executed on the CPython virtual machine evaluation loop (`ceval.c`).",
            "Design a thread-safe connection pool in Python with maximum connection limits, acquisition timeouts, and automatic connection health recovery.",
            "How does `asyncio` handle cancellation exceptions (`asyncio.CancelledError`), and how do you ensure cleanup resources are freed safely during shutdown?",
            "Walk through how Python's garbage collector detects reference cycles in generation 0, 1, and 2 using double-linked lists of container objects.",
            "How would you build an asynchronous distributed rate limiter using Python `asyncio` and Redis atomic Lua scripts handling 50,000 requests/second?",
            "Explain how the `mmap` module in Python allows zero-copy file reading and sharing memory between concurrent Python processes.",
            "How does Python's `inspect` module and frame objects (`sys._getframe`) allow introspection of calling stacks and local variables?",
            "Compare green threads / coroutines (gevent, eventlet) with native Python `async`/`await` in terms of monkey-patching risks and stack frame overhead.",
            "Design a resilient message consumer in Python using `aiokafka` that guarantees at-least-once processing semantics and handles worker rebalances.",
            "How do you implement custom memory allocators in Python for high-performance scientific data structures using `ctypes` or `cffi`?",
            "Analyze the GIL removal initiative (PEP 703 free-threaded Python) in CPython: how does biased reference counting and mimalloc replace the global lock?"
        ]
    }
}
