"""
Comprehensive Question Banks for AI Interview Coach
Provides up to 20 distinct, sequential questions across Easy, Medium, and Hard
for DSA, Machine Learning, System Design, Python, and General Engineering.
"""
from typing import Dict, List

EXPANDED_QUESTION_BANKS: Dict[str, Dict[str, List[str]]] = {
    "dsa": {
        "Easy": [
            "### Problem: Two Sum\nGiven an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`.\n\n**Test Cases:**\n- `nums = [2, 7, 11, 15], target = 9` ➔ `[0, 1]`\n- `nums = [3, 2, 4], target = 6` ➔ `[1, 2]`\n\n**Requirements:** State Time ($O(N)$) and Space ($O(N)$) complexity.",
            "### Problem: Valid Anagram\nGiven two strings `s` and `t`, return `true` if `t` is an anagram of `s`, and `false` otherwise.\n\n**Test Cases:**\n- `s = \"anagram\", t = \"nagaram\"` ➔ `true`\n- `s = \"rat\", t = \"car\"` ➔ `false`\n\n**Requirements:** Solve in $O(N)$ Time. Can you do it in $O(1)$ auxiliary space for ASCII?",
            "### Problem: Reverse Linked List\nGiven the `head` of a singly linked list, reverse the list, and return the reversed list.\n\n**Test Cases:**\n- `head = [1, 2, 3, 4, 5]` ➔ `[5, 4, 3, 2, 1]`\n- `head = []` ➔ `[]`\n\n**Requirements:** Walk through iterative pointer updates in $O(1)$ space.",
            "### Problem: Binary Search\nGiven a sorted array `nums` and `target`, return index or `-1`.\n\n**Test Cases:**\n- `nums = [-1, 0, 3, 5, 9, 12], target = 9` ➔ `4`\n\n**Requirements:** Why calculate `mid = left + (right - left) // 2`? State Time ($O(\\log N)$).",
            "### Problem: Merge Two Sorted Lists\nMerge two sorted linked lists and return it as a new sorted list.\n\n**Requirements:** Maintain $O(1)$ auxiliary space by relinking existing nodes.",
            "### Problem: Maximum Subarray (Kadane's Algorithm)\nFind the contiguous subarray which has the largest sum and return its sum.\n\n**Test Cases:** `[-2,1,-3,4,-1,2,1,-5,4]` ➔ `6` (`[4,-1,2,1]`). State $O(N)$ approach.",
            "### Problem: Valid Parentheses\nGiven a string `s` containing just `'('`, `')'`, `'{'`, `'}'`, `'['` and `']'`, determine if the input string is valid using a stack.",
            "### Problem: Contains Duplicate\nReturn `true` if any value appears at least twice in the array.\n\n**Requirements:** Compare Hash Set ($O(N)$ time, $O(N)$ space) vs Sorting ($O(N \\log N)$ time, $O(1)$ space).",
            "### Problem: Climbed Stairs (Fibonacci DP)\nYou are climbing a staircase. It takes `n` steps to reach the top. Each time you can climb 1 or 2 steps. How many distinct ways can you climb to the top?",
            "### Problem: Best Time to Buy and Sell Stock\nMaximize profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock in $O(N)$ time.",
            "### Problem: Invert Binary Tree\nGiven the root of a binary tree, invert the tree, and return its root.",
            "### Problem: Linked List Cycle\nDetermine if a linked list has a cycle using Floyd's Tortoise and Hare two-pointer algorithm in $O(1)$ memory.",
            "### Problem: Middle of the Linked List\nReturn the middle node of the linked list using fast and slow pointers in one pass.",
            "### Problem: Majority Element\nGiven an array `nums` of size `n`, return the majority element that appears more than $\\lfloor n/2 \\rfloor$ times using Boyer-Moore Voting Algorithm ($O(1)$ space).",
            "### Problem: Move Zeroes\nGiven an integer array `nums`, move all 0's to the end of it while maintaining the relative order of the non-zero elements in-place.",
            "### Problem: Single Number\nEvery element appears twice except for one. Find that single one in linear time and $O(1)$ memory using Bitwise XOR.",
            "### Problem: Diameter of Binary Tree\nCompute the length of the longest path between any two nodes in a tree.",
            "### Problem: Symmetric Tree\nCheck whether a binary tree is a mirror of itself (symmetric around its center) recursively and iteratively.",
            "### Problem: Roman to Integer\nConvert a Roman numeral string to an integer handling subtractive instances (`IV`, `IX`, `XL`, `XC`, `CD`, `CM`).",
            "### Problem: Palindrome Linked List\nDetermine if a singly linked list is a palindrome in $O(N)$ time and $O(1)$ space by reversing the second half."
        ],
        "Medium": [
            "### Problem: Longest Substring Without Repeating Characters\nFind the length of the longest substring without duplicate characters using sliding window and a hash map.\n\n**Test Cases:** `\"abcabcbb\"` ➔ `3` (`\"abc\"`). State Time ($O(N)$) and Space.",
            "### Problem: LRU Cache Design\nDesign a data structure with $O(1)$ average time for both `get` and `put` using a Hash Map and Doubly Linked List.",
            "### Problem: Number of Islands\nGiven an `m x n` binary grid, count the number of islands using BFS or DFS in $O(M \\times N)$ time.",
            "### Problem: Course Schedule (Cycle Detection)\nReturn `true` if you can finish all courses given prerequisites using Kahn's topological sort or DFS 3-coloring.",
            "### Problem: 3Sum\nFind all unique triplets `[nums[i], nums[j], nums[k]]` that sum to 0 in $O(N^2)$ time with two pointers.",
            "### Problem: Group Anagrams\nGroup an array of strings that are anagrams together using sorted string keys or 26-character frequency tuples.",
            "### Problem: Product of Array Except Self\nReturn an array `answer` such that `answer[i]` is equal to the product of all elements except `nums[i]` without using division in $O(N)$ time and $O(1)$ auxiliary space.",
            "### Problem: Coin Change\nFind the minimum number of coins needed to make up a given amount using Dynamic Programming (`dp[i] = min(dp[i], dp[i - c] + 1)`).",
            "### Problem: Kth Largest Element in an Array\nFind the `k`th largest element using QuickSelect ($O(N)$ average) or Min-Heap of size `k` ($O(N \\log K)$).",
            "### Problem: Word Break\nGiven string `s` and dictionary `wordDict`, determine if `s` can be segmented into dictionary words using DP and a Trie.",
            "### Problem: Lowest Common Ancestor in Binary Tree\nFind the LCA of two nodes `p` and `q` in a binary tree in $O(N)$ time.",
            "### Problem: Validate Binary Search Tree\nDetermine if a binary tree is a valid BST using boundary range tracking `(low, high)` or in-order traversal.",
            "### Problem: Rotting Oranges\nFind minimum minutes until no fresh orange remains using Multi-Source BFS.",
            "### Problem: Daily Temperatures\nReturn an array such that `answer[i]` is the number of days until a warmer temperature using a Monotonic Decreasing Stack.",
            "### Problem: Permutations\nGiven an array `nums` of distinct integers, return all possible permutations using backtracking.",
            "### Problem: Subarray Sum Equals K\nFind the total number of continuous subarrays whose sum equals `k` using a prefix sum frequency hash map in $O(N)$ time.",
            "### Problem: Pacific Atlantic Water Flow\nFind all grid coordinates that can flow water to both oceans using reverse BFS/DFS from ocean boundaries.",
            "### Problem: Search in Rotated Sorted Array\nSearch `target` in an array sorted in ascending order then rotated at an unknown pivot in $O(\\log N)$ time.",
            "### Problem: Clone Graph\nReturn a deep copy of a connected undirected graph using BFS/DFS with a cloned node hash map.",
            "### Problem: Top K Frequent Elements\nReturn the `k` most frequent elements in $O(N)$ time using Bucket Sort or $O(N \\log K)$ with a min-heap."
        ],
        "Hard": [
            "### Problem: Trapping Rain Water\nCompute water volume trapped between elevation bars in $O(N)$ time and $O(1)$ auxiliary space using two pointers.",
            "### Problem: Median of Two Sorted Arrays\nFind the median of two sorted arrays in $O(\\log(\\min(m, n)))$ time using binary search partitioning.",
            "### Problem: Sliding Window Maximum\nReturn max for each window of size `k` in amortized $O(N)$ time using a monotonic decreasing deque.",
            "### Problem: Word Ladder II\nFind all shortest transformation sequences from `beginWord` to `endWord` using Bidirectional BFS + DFS Backtracking.",
            "### Problem: Merge K Sorted Lists\nMerge `k` sorted linked lists in $O(N \\log K)$ time using a Priority Queue / Divide and Conquer.",
            "### Problem: Alien Dictionary\nDerive character ordering from an alien dictionary using Directed Graph Topological Sorting and cycle detection.",
            "### Problem: Minimum Window Substring\nFind the minimum window in `s` which will contain all characters in `t` in $O(N)$ time using sliding window with frequency match counter.",
            "### Problem: Serialize and Deserialize Binary Tree\nDesign an algorithm to serialize a binary tree into a string and deserialize it back using Pre-order DFS or Level-order BFS.",
            "### Problem: Largest Rectangle in Histogram\nFind the area of the largest rectangle in a histogram in $O(N)$ time using a monotonic increasing stack.",
            "### Problem: First Missing Positive\nFind the smallest missing positive integer in $O(N)$ time and $O(1)$ auxiliary space using in-place cyclic bucket placement.",
            "### Problem: N-Queens\nPlace `n` queens on an `n x n` chessboard so that no two queens attack each other using backtracking and diagonal bitmasks.",
            "### Problem: Regular Expression Matching\nImplement regex matching with support for `'.'` and `'*'` using 2D Dynamic Programming.",
            "### Problem: Binary Tree Maximum Path Sum\nFind the maximum path sum between any two nodes in a binary tree in $O(N)$ time.",
            "### Problem: Longest Valid Parentheses\nFind the length of the longest valid (well-formed) parentheses substring using a stack or two-pass counter in $O(1)$ space.",
            "### Problem: Bus Routes\nFind the least number of buses to travel from `source` to `target` using BFS on bus route graphs.",
            "### Problem: Edit Distance (Levenshtein Distance)\nFind minimum operations (insert, delete, replace) to convert `word1` to `word2` using 2D DP in $O(M \\times N)$ time.",
            "### Problem: Critical Connections in a Network\nFind bridges in an undirected network using Tarjan's DFS algorithm with discovery and lowest rank tracking.",
            "### Problem: Swim in Rising Water\nFind least time until you can reach the bottom right cell in a grid using Dijkstra / Priority Queue BFS.",
            "### Problem: Distinct Subsequences\nGiven two strings `s` and `t`, return number of distinct subsequences of `s` which equals `t` using DP.",
            "### Problem: Text Justification\nFormat an array of words into lines of width `maxWidth` with fully justified text."
        ]
    },
    "machine learning": {
        "Easy": [
            "Can you explain the fundamental difference between supervised, unsupervised, and reinforcement learning with real-world examples?",
            "What is the bias-variance tradeoff, and how does model complexity directly influence underfitting vs overfitting?",
            "What is the mathematical difference between L1 (Lasso) and L2 (Ridge) regularization, and why does L1 lead to sparse feature selection?",
            "Explain precision, recall, and F1-score. When would you optimize strictly for recall over precision?",
            "Can you walk me through how gradient descent iteratively minimizes a model's loss function?",
            "What is the role of activation functions in neural networks, and why is ReLU preferred over Sigmoid in hidden layers?",
            "Explain cross-validation (K-Fold) and why evaluating solely on a single train-test split can lead to overly optimistic metrics.",
            "What is the difference between classification and regression, and what loss functions are standard for each?",
            "How does logistic regression map unbounded linear outputs to probabilities between 0 and 1 using the sigmoid function?",
            "What is the curse of dimensionality, and how does increasing feature count affect distance metrics in algorithms like KNN?",
            "Explain the difference between parametric and non-parametric machine learning models with examples.",
            "What is data leakage, and how does standardizing features before performing train-test splitting cause leakage?",
            "How does a Decision Tree decide where to split a node (Gini Impurity vs Information Gain / Entropy)?",
            "What is the Receiver Operating Characteristic (ROC) curve, and how is Area Under the Curve (AUC) interpreted?",
            "Explain the difference between covariance and correlation, and why correlation is normalized between -1 and 1.",
            "What is one-hot encoding vs target encoding, and when would one-hot encoding lead to excessive sparsity?",
            "How do outliers impact Mean Squared Error (MSE) compared to Mean Absolute Error (MAE)?",
            "What is the purpose of a validation set distinct from both training and test sets?",
            "Explain the concept of learning rate in optimization: what happens when it is too high versus too low?",
            "What is early stopping in model training, and how does tracking validation loss prevent overfitting?"
        ],
        "Medium": [
            "In a real-time credit card fraud detection dataset where fraudulent transactions make up only 0.1% of samples, what sampling techniques and evaluation metrics would you use?",
            "Explain the core differences between bagging and boosting, specifically comparing Random Forests with Gradient Boosted Decision Trees (XGBoost/LightGBM).",
            "Walk me through the architectural and mathematical difference between Batch Normalization and Layer Normalization. Why is LayerNorm standard in Transformers?",
            "How do you detect and prevent target leakage in a multi-stage time-series feature engineering pipeline?",
            "If training loss is consistently decreasing but validation loss diverges after epoch 12, what concrete diagnostic steps and remedies would you apply?",
            "How does the self-attention mechanism in Transformers compute attention weights mathematically ($Q, K, V$ matrices and $\\text{softmax}(QK^T / \\sqrt{d_k})$)?",
            "Compare Word2Vec embeddings (Skip-gram / CBOW) with contextual Transformer embeddings (BERT). How do they handle polysemy?",
            "Explain the Vanishing and Exploding Gradient problem in deep networks. What mathematical mechanisms in LSTMs and ResNet skip connections mitigate it?",
            "How would you evaluate and calibrate a machine learning model whose predicted probabilities are poorly calibrated (Platt scaling vs Isotonic regression)?",
            "Describe the mathematical mechanics of Principal Component Analysis (PCA) through eigendecomposition / SVD of the covariance matrix.",
            "When building an ML recommendation system, how do you solve the cold start problem for newly onboarded users and items?",
            "What is the mathematical formulation of Focal Loss, and why does down-weighting easy examples improve object detection / class imbalance?",
            "Compare Stochastic Gradient Descent (SGD) with momentum against adaptive optimizers like Adam and RMSprop.",
            "How do you handle covariate shift and concept drift in a production ML model serving real-time predictions?",
            "Explain Dropout regularization during training versus inference: why must activations be scaled by $1 - p$ during evaluation?",
            "How would you structure a multi-task learning architecture where a single backbone shares representations across two distinct prediction heads?",
            "What is the difference between generative and discriminative modeling, contrasting Naive Bayes with Logistic Regression?",
            "How do you perform hyperparameter tuning efficiently at scale (Random Search vs Bayesian Optimization with Gaussian Processes)?",
            "Explain K-Means clustering convergence criteria, the elbow method, and how K-Means++ initialization avoids suboptimal local minima.",
            "In natural language processing, how does Byte-Pair Encoding (BPE) tokenize out-of-vocabulary words into subwords?"
        ],
        "Hard": [
            "Analyze the memory bandwidth, IO-awareness, and computational efficiency improvements of FlashAttention compared to standard multi-head attention.",
            "How would you design a real-time recommendation engine serving 50,000 queries per second with sub-40ms latency, balancing two-stage retrieval (ANN/embeddings) and ranking?",
            "Compare fine-tuning strategies for Large Language Models: Full fine-tuning vs LoRA vs QLoRA vs Prefix Tuning, analyzing GPU VRAM, parameter efficiency, and catastrophic forgetting.",
            "How would you architect a distributed model training cluster across multi-node GPU instances, comparing Data Parallelism (DDP), Fully Sharded Data Parallel (FSDP), and Tensor Parallelism?",
            "Design an automated ML observability pipeline to monitor covariate shift and concept drift on high-velocity production data streams.",
            "Walk through Direct Preference Optimization (DPO) vs Reinforcement Learning from Human Feedback (RLHF with PPO) for aligning foundation language models.",
            "How does Rotary Position Embedding (RoPE) encode relative position information mathematically into query and key representations?",
            "Design a vector search similarity engine indexing 1 billion 768-dimensional embeddings with sub-10ms recall, comparing HNSW, IVF-PQ, and ScaNN.",
            "Explain KV-Cache optimization in LLM text generation: how does PagedAttention eliminate memory fragmentation in vLLM serving engines?",
            "How would you train a diffusion model (DDPM / DDIM) for image generation, explaining the forward noise schedule, score matching, and reverse denoising U-Net?",
            "Analyze speculative decoding in Large Language Models: how does a smaller draft model accelerate token generation without changing target distribution?",
            "How would you detect and remediate adversarial attacks (FGSM, PGD) designed to perturb image classifiers or LLM jailbreaks?",
            "Design a real-time feature store (like Feast / Hopsworks) that guarantees point-in-time correctness for training and sub-5ms low-latency feature retrieval for inference.",
            "Explain Mixture of Experts (MoE) routing mechanisms (Top-K gating, load balancing auxiliary loss) in models like Mixtral.",
            "How does Grouped-Query Attention (GQA) reduce memory bandwidth during LLM decoding compared to Multi-Head Attention and Multi-Query Attention?",
            "Walk through contrastive representation learning in CLIP (InfoNCE loss formulation) and how cross-modal temperature parameter modulates gradients.",
            "How would you benchmark and quantize a 70B parameter model from FP16 to INT4 (AWQ vs GPTQ) while preserving perplexity on complex reasoning benchmarks?",
            "Design an end-to-end continuous retraining pipeline with automated canary evaluation, shadow deployment, and automated rollback upon metric regression.",
            "Explain the mathematical formulation of Neural ODEs and how adjoint sensitivity method allows backpropagation through ODE solvers with $O(1)$ memory.",
            "How do you implement distributed asynchronous parameter servers for trillion-parameter sparse embedding tables in click-through rate (CTR) prediction?"
        ]
    },
    "system design": {
        "Easy": [
            "What is the core difference between horizontal scaling and vertical scaling, and what are their respective limits?",
            "Can you explain the CAP theorem and why distributed networks must choose between Consistency and Availability during network partitions?",
            "What is the difference between relational SQL databases and NoSQL databases, and what are common NoSQL data models?",
            "What is a reverse proxy (e.g., Nginx, Envoy) and what critical advantages does it provide in modern web architectures?",
            "How does DNS resolution translate a domain name into an IP address from browser cache to authoritative name servers?",
            "What is a Content Delivery Network (CDN), and how does edge caching reduce latency for static assets?",
            "Explain the difference between synchronous HTTP communication and asynchronous message passing with message queues.",
            "What is database replication (Leader-Follower), and how does read-scaling work across follower nodes?",
            "What is a Load Balancer, and what are common routing algorithms (Round Robin, Least Connections, IP Hash)?",
            "Explain database indexing using B-Trees: why does an index accelerate read queries while adding latency to write operations?",
            "What is caching, and how does the Cache-Aside pattern work in conjunction with an application server?",
            "What is the difference between stateless and stateful service architectures, and why are stateless servers easier to scale horizontally?",
            "What is database connection pooling, and why is creating a fresh TCP connection per request a bottleneck?",
            "Explain the difference between REST, GraphQL, and gRPC for client-server communication.",
            "What is an API Gateway, and what responsibilities does it consolidate (rate limiting, authentication, SSL termination)?",
            "What is database sharding (horizontal partitioning), and what is a shard key?",
            "Explain what a single point of failure (SPOF) is and how redundancy eliminates it.",
            "What is the difference between throughput (QPS / RPS) and latency (p50, p95, p99)?",
            "What is data serialization (JSON vs Protocol Buffers vs Avro), and how does binary serialization save network bandwidth?",
            "Explain polling vs Long-Polling vs WebSockets vs Server-Sent Events (SSE) for real-time web applications."
        ],
        "Medium": [
            "Design a URL shortening service like bit.ly capable of handling 20,000 writes/sec and 200,000 reads/sec. How do you generate unique IDs and guarantee low-latency redirects?",
            "Explain how consistent hashing works and how virtual nodes prevent hot-spotting when cache nodes are added or removed dynamically.",
            "How would you implement a distributed API rate limiter supporting 100,000 req/sec using Redis? Which algorithm (token bucket, sliding window counter) would you pick and why?",
            "Describe caching strategies (Cache-Aside, Write-Through, Write-Behind) for an e-commerce catalog, and explain how to mitigate cache stampedes (thundering herd).",
            "How does Apache Kafka guarantee message ordering, and what trade-offs exist between partition count, consumer concurrency, and strict FIFO delivery?",
            "Design a distributed unique ID generator producing 64-bit strictly monotonic IDs (like Twitter Snowflake).",
            "Architect a notification service delivering push, SMS, and email notifications to 50 million users daily with rate limits and delivery prioritization.",
            "Design an e-commerce flash sale system handling 100,000 users attempting to buy 1,000 inventory items simultaneously without overselling.",
            "How do you implement distributed transactions across microservices using the Saga pattern (Choreography vs Orchestration)?",
            "Design an image and video upload processing pipeline with thumbnail generation, deduplication, and secure S3 presigned URLs.",
            "Compare relational ACID transactions with BASE (Basically Available, Soft state, Eventual consistency) distributed models.",
            "Design a Web Crawler capable of crawling 100 million web pages weekly while respecting robots.txt and handling domain politeness.",
            "How do database isolation levels (Read Committed, Repeatable Read, Serializable) prevent dirty reads, non-repeatable reads, and phantom reads?",
            "Design a Pastebin service allowing users to store and share text snippets with customizable expiration TTLs and access analytics.",
            "How does a distributed cache cluster handle cache invalidation and cache penetration with Bloom filters?",
            "Design a metrics collection and monitoring system (like Prometheus) storing time-series data with downsampling and alerting.",
            "Explain the difference between Optimistic Concurrency Control (version checking) and Pessimistic Locking in database transactions.",
            "Design a key-value store with read repair, hinted handoff, and tunable consistency levels (Cassandra model).",
            "How do you architect a secure multi-tenant SaaS database (separate database per tenant vs shared database with tenant ID column)?",
            "Design a top-K trending topics service that computes most frequent hashtags in real-time over a sliding 1-hour window."
        ],
        "Hard": [
            "Architect a real-time collaborative document editing system (like Google Docs) supporting concurrent offline and online edits. Compare Operational Transformation (OT) vs CRDTs.",
            "Design a globally distributed payment transaction ledger ensuring strict ACID compliance, idempotency, and multi-region disaster recovery.",
            "How would you design an event-driven stream processing platform handling 2 million events per second with exactly-once processing semantics under worker node crashes?",
            "Design a multi-region active-active database architecture with conflict resolution for a mission-critical banking application with RPO < 1s and RTO < 30s.",
            "How would you architect a distributed search and log analytics engine across petabytes of data with sub-second query latency?",
            "Design a distributed message broker from scratch: Explain commit log storage layout, zero-copy OS transfers (`sendfile`), and consumer offset checkpointing.",
            "How do distributed consensus algorithms (Raft vs Paxos) achieve leader election, log replication, and safe recovery during network splits?",
            "Design a global video streaming platform (like Netflix) with adaptive bitrate transcoding, dynamic CDN edge steering, and edge session tokens.",
            "Architect a real-time ride-sharing dispatch system (like Uber) handling location updates from 2 million active drivers and matching riders in under 20ms.",
            "Design a distributed database query engine (like Presto/Trino) executing federated SQL queries across heterogeneous distributed data sources.",
            "How would you architect a zero-downtime database migration strategy from a legacy Oracle monolith to a distributed CockroachDB cluster with zero data loss?",
            "Design a distributed lock manager (like Redlock / Google Chubby / ZooKeeper) and prove safety guarantees under asynchronous network delays and GC pauses.",
            "Architect an ad-click aggregation and real-time fraud detection pipeline processing 500,000 clicks/sec with micro-batch windowing and deduplication.",
            "Design a distributed file system (like Google GFS / HDFS) addressing master bottleneck, chunk replication, heartbeat monitoring, and split-brain resolution.",
            "How would you design a global content recommendation feed serving 200 million daily active users with personalization, deduplication, and diversity reranking?",
            "Architect an enterprise disaster recovery architecture: compare active-passive with pilot light vs active-active multi-cloud deployment.",
            "Design a real-time multiplayer gaming server architecture handling synchronization, dead reckoning interpolation, and UDP packet loss.",
            "How do you implement distributed tracing (OpenTelemetry / Jaeger) across 5,000 microservices without degrading network throughput or storage budgets?",
            "Design an automated database auto-sharding and rebalancing engine that splits and migrates partitions without dropping active client connections.",
            "Architect a high-frequency trading (HFT) matching engine with sub-microsecond order execution, deterministic order book matching, and audit logging."
        ]
    },
    "python": {
        "Easy": [
            "Can you explain the difference between a list and a tuple in Python, particularly regarding mutability and memory allocation?",
            "What is the Global Interpreter Lock (GIL) in CPython and how does it impact multi-threaded CPU-bound programs?",
            "How do Python dictionaries handle key collisions under the hood, and what are the requirements for an object to be used as a dictionary key?",
            "What is the difference between shallow copy (`copy.copy`) and deep copy (`copy.deepcopy`) in Python?",
            "How does Python manage memory and clean up unused objects? Can you explain reference counting and cyclic garbage collection?",
            "What are Python list comprehensions, and why are they generally faster than standard for-loops with `.append()`?",
            "Explain the difference between `is` and `==` in Python with examples (including integer caching).",
            "What are `*args` and `**kwargs` in Python function definitions, and how does argument unpacking work?",
            "What is the purpose of `__init__` and `self` in Python class definitions?",
            "Explain how the `with` statement and context managers work using `__enter__` and `__exit__`.",
            "What is the difference between `range()` and a list in Python 3 in terms of memory efficiency?",
            "How does Python handle exceptions with `try`, `except`, `else`, and `finally` blocks?",
            "What are lambda functions in Python, and what are their limitations compared to standard `def` functions?",
            "Explain the difference between static methods (`@staticmethod`), class methods (`@classmethod`), and instance methods.",
            "What are Python sets, how are they implemented under the hood, and what are their lookup time bounds?",
            "What is string immutability in Python, and why is repeated `+` string concatenation in a loop an antipattern?",
            "How do Python modules and packages work, and what is the role of `__init__.py`?",
            "Explain the built-in functions `zip()`, `map()`, and `filter()` with practical examples.",
            "What is the difference between `append()` and `extend()` on Python lists?",
            "What is duck typing in Python, and what does the phrase 'Easier to ask for forgiveness than permission' (EAFP) mean?"
        ],
        "Medium": [
            "How would you implement a custom function decorator with arguments in Python that logs execution time in milliseconds?",
            "Explain how Python generators and the `yield` keyword work. In what production scenario would you prefer a generator over a list comprehension?",
            "When designing high-throughput I/O tasks in Python, how do you decide between `asyncio`, `multiprocessing`, and `concurrent.futures.ThreadPoolExecutor`?",
            "How does Python resolve multiple inheritance method calls (Method Resolution Order / C3 Linearization)?",
            "How would you process a 15GB CSV file in Python on a worker machine constrained to 2GB of RAM without crashing?",
            "Explain Python descriptors (`__get__`, `__set__`, `__delete__`) and how `@property` is built on top of the descriptor protocol.",
            "What are metaclasses in Python (`type`), and how do frameworks like Pydantic or Django ORM use metaclasses to inspect class definitions?",
            "How does `asyncio` event loop execute tasks concurrently on a single thread? What is the difference between `asyncio.gather` and `asyncio.wait`?",
            "Explain how Python's `collections.defaultdict`, `Counter`, and `deque` optimize standard data workflows.",
            "How do `__slots__` optimize memory in Python classes with millions of instantiated objects?",
            "What is the difference between `pickle` and `json` serialization in Python, and what are the security vulnerabilities of unpickling untrusted data?",
            "How would you write a custom context manager in Python using the `@contextlib.contextmanager` decorator?",
            "Explain monkey patching in Python: how does it work, when is it useful for testing, and what risks does it introduce in production?",
            "How does CPython optimize small integers (-5 to 256) and string interning?",
            "Explain the difference between `threading.Lock` and `threading.RLock` (reentrant lock) in Python.",
            "How would you implement an LRU cache decorator from scratch in Python without using `functools.lru_cache`?",
            "What is the purpose of the `weakref` module in Python, and how does it prevent circular reference memory leaks?",
            "How do type hints and the `typing` module (Generics, Union, Protocol) integrate with static type checkers like `mypy`?",
            "Explain the difference between `os.fork()`, `multiprocessing.Process`, and `subprocess.Popen` in Unix environments.",
            "How do abstract base classes (`abc.ABC` and `@abstractmethod`) enforce interface contracts in Python?"
        ],
        "Hard": [
            "Explain the low-level memory allocation hierarchy of CPython (arenas, pools, blocks) and how small object allocation (`PyObject_Malloc`) avoids system malloc overhead.",
            "If you were architecting a distributed asynchronous task queue like Celery from scratch in Python, how would you handle worker heartbeats, acknowledgment guarantees, and prefetch limits?",
            "Analyze the trade-offs of using `asyncio` event loops vs thread pools when integrating legacy synchronous database drivers with an asynchronous web framework like FastAPI.",
            "How would you design a hot-reloading plugin system in Python that dynamically imports modules without memory leaks or namespace contamination?",
            "Compare the performance characteristics and execution models of CPython vs PyPy vs Cython for CPU-bound computational workloads.",
            "How would you profile CPU bottlenecks and memory leaks in a live Python production service using `py-spy`, `cProfile`, and `tracemalloc`?",
            "Explain the internal implementation of Python dictionary lookup in CPython 3.6+ (compact dict structure separating hash table entries from key-value pairs).",
            "How does the sub-interpreter model (PEP 554 / PEP 684 per-interpreter GIL) provide multi-core concurrency in Python 3.12+?",
            "How would you write a C-extension for Python using the Python C-API to accelerate a matrix multiplication algorithm by 50x?",
            "Explain how Python bytecode is generated, compiled, and executed on the CPython virtual machine evaluation loop (`ceval.c`).",
            "Design a thread-safe connection pool in Python with maximum connection limits, acquisition timeouts, and automatic connection health recovery.",
            "How does `asyncio` handle cancellation exceptions (`asyncio.CancelledError`), and how do you ensure cleanup resources are freed safely during shutdown?",
            "Walk through how Python's garbage collector detects reference cycles in generation 0, 1, and 2 using double-linked lists of container objects.",
            "How would you build an asynchronous distributed rate limiter using Python `asyncio` and Redis atomic Lua scripts handling 50,000 requests/second?",
            "Explain how the `mmap` module in Python allows zero-copy file reading and sharing memory between concurrent Python processes.",
            "How does Python's `inspect` module and frame objects (`sys._getframe`) allow introspection of calling stacks and local variables?",
            "Compare green threads / coroutines (gevent, eventlet) with native Python `async`/`await` in terms of monkey-patching risks and stack frame overhead.",
            "Design a resilient message consumer in Python using `aiokafka` that guarantees at-least-once processing semantics and handles worker rebalances.",
            "How do you implement custom memory allocators in Python for high-performance scientific data structures using `ctypes` or `cffi`?",
            "Analyze the GIL removal initiative (PEP 703 free-threaded Python) in CPython: how does biased reference counting and mimalloc replace the global lock?"
        ]
    }
}
